version: '2'
services:  
  mongodb:
    image: mongo:3.6
    container_name: mongo
    ports:
     - 27015:27017
  app:
    restart: always
    image: prashantchintaldockerid/springboot-graphql
    expose:
      - "8090"
    environment:
      - "spring.data.mongodb.host=mongo"
    links:
      - mongodb
    depends_on:
      - mongodb
