version: '2'
services:  
  mongodb:
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27015:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  app:
    restart: always
    image: amitmindstix/graphql-java:v2
    expose:
      - "8090"
    environment:
      - "spring.data.mongodb.host=mongodb"
    links:
      - mongodb
    depends_on:
      - mongodb
