spring.jmx:
   enabled: false

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: app1
        
server:
  port: 8090

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

